# Generated by Django 3.2.8 on 2021-10-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
