# Generated by Django 3.2.8 on 2021-10-26 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_commentaire_instagrammeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagrameur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('pseudo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('mdp', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='instagrammeur',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='commentateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagramapp.instagrameur'),
        ),
    ]
