# Generated by Django 3.2.8 on 2021-10-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0003_auto_20211026_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
